name: Tests

on:
  push:
    branches-ignore: 
      - main

jobs:
  tests:
    strategy:
      matrix:
        ruby: [2.5, 2.6, 2.7, 3.0]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: DEBUG
      run: bundle config list 
    - name: CLEAN
      run: bundle config unset path 
    - name: Run linter
      run: bundle exec rubocop -c ./.rubocop.yml
    - name: Run tests
      run: bundle exec rspec
