name: Tests

on:
  push:
    branches-ignore: 
      - main

jobs:
  tests:
    strategy:
      matrix:
        ruby: [2.5, 2.6, 2.7, 3.0]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Cache ruby gems
      uses: actions/cache@v2
      env:
        cache-name: cache-gems
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-build-${{ env.cache-name }}-ruby-${{ matrix.ruby }}-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-ruby-${{ matrix.ruby }}
    - name: Install dependencies
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: Run linter
      run: bundle exec rubocop
    - name: Run tests
      run: bundle exec rspec
